version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge